apiVersion: v1
kind: Pod
metadata:
  name: app-secretenv
spec:
  containers:
    - name: app-secretenv
      image: redis
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password