apiVersion: v1
kind: Pod
metadata:
  name: app-resources
spec:
  containers:
  - name: app-resources
    image: my-app
    resources:
      requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"