apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjob
              image: cronjob-image
              command: ["/bin/sh"]
              args: ["-c", "Hello CronJob"]
          restartPolicy: OnFailure